# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Why Spiking?
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Our Manifesto on why spiking neural networks have a place in the world of machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whyspiking.github.io" # the base hostname & protocol for your site
github_username:  whyspiking

# Build settings
markdown: kramdown
